site_name: Extrusora de Plástico
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
# Use the ReadTheDocs theme
theme:
  name: material
  highlightjs: true 
  palette:
        
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode


  
      - media: "(prefers-color-scheme: light)"
        scheme: default 
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

 
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference

  features:
    - content.code.copy
    - content.tooltips
    - navigation.top       # Menú superior
    - navigation.sections  # Secciones en la izquierda
    - toc.integrate        # Integra el índice en el panel izquierdo
    - toc.follow           # Índice fijo en la derecha
extra_css:
  - https://use.fontawesome.com/releases/v6.5.2/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
nav:
  - Inicio: index.md
  - Presentación: presentacion.md
  - Plástico PLA: plasticopla.md
  - Funcionamiento de la extrusora: funcionamientoextrusora.md
  - Componentes principales: componentes.md
  - Contacto: contacto.md
  - Referencias: referencias.md

